using System;
using System.Collections.Generic;

namespace Entities.Concrete
{
    public partial class OtomailRpgirisciki
    {
        public int Idno { get; set; }
        public string? Prsicilno { get; set; }
        public string? Pradi { get; set; }
        public string? Prsoyadi { get; set; }
        public string? Prkartno { get; set; }
        public DateTime? Prkrttar { get; set; }
        public DateTime? Prisgirt { get; set; }
        public DateTime? Priscikt { get; set; }
        public string? Prcikndn { get; set; }
        public string? Csturu { get; set; }
        public DateTime? Prtpgirt { get; set; }
        public int? Prposta { get; set; }
        public string? Psadi { get; set; }
        public DateTime? Prpostar { get; set; }
        public string? Prdepart { get; set; }
        public string? Dpadi { get; set; }
        public DateTime? Prdeptar { get; set; }
        public string? Prkadro { get; set; }
        public string? Kdturu { get; set; }
        public string? Prmeslek { get; set; }
        public string? Msturu { get; set; }
        public string? Prpertip { get; set; }
        public string? Ptturu { get; set; }
        public string? Prpuantb { get; set; }
        public string? Prmesai { get; set; }
        public string? Prgorev { get; set; }
        public string? Grturu { get; set; }
        public string? Prservis { get; set; }
        public string? Srturu { get; set; }
        public string? Prgmyaka { get; set; }
        public string? Prkod1 { get; set; }
        public string? Prkod2 { get; set; }
        public string? Praltdepart { get; set; }
        public string? Adadadi { get; set; }
        public DateTime? Praltdeptar { get; set; }
        public string? Prmasraf { get; set; }
        public string? Mmturu { get; set; }
        public DateTime? Prmasraftar { get; set; }
        public DateTime? Tarih { get; set; }
        public DateTime? Gtarih1 { get; set; }
        public DateTime? Gzaman1 { get; set; }
        public string? Gkapi1 { get; set; }
        public string? Gneden1 { get; set; }
        public DateTime? Ctarih1 { get; set; }
        public DateTime? Czaman1 { get; set; }
        public string? Ckapi1 { get; set; }
        public string? Cneden1 { get; set; }
        public DateTime? Gtarih2 { get; set; }
        public DateTime? Gzaman2 { get; set; }
        public string? Gkapi2 { get; set; }
        public string? Gneden2 { get; set; }
        public DateTime? Ctarih2 { get; set; }
        public DateTime? Czaman2 { get; set; }
        public string? Ckapi2 { get; set; }
        public string? Cneden2 { get; set; }
        public DateTime? Gtarih3 { get; set; }
        public DateTime? Gzaman3 { get; set; }
        public string? Gkapi3 { get; set; }
        public string? Gneden3 { get; set; }
        public DateTime? Ctarih3 { get; set; }
        public DateTime? Czaman3 { get; set; }
        public string? Ckapi3 { get; set; }
        public string? Cneden3 { get; set; }
        public DateTime? Gtarih4 { get; set; }
        public DateTime? Gzaman4 { get; set; }
        public string? Gkapi4 { get; set; }
        public string? Gneden4 { get; set; }
        public DateTime? Ctarih4 { get; set; }
        public DateTime? Czaman4 { get; set; }
        public string? Ckapi4 { get; set; }
        public string? Cneden4 { get; set; }
        public DateTime? Gtarih5 { get; set; }
        public DateTime? Gzaman5 { get; set; }
        public string? Gkapi5 { get; set; }
        public string? Gneden5 { get; set; }
        public DateTime? Ctarih5 { get; set; }
        public DateTime? Czaman5 { get; set; }
        public string? Ckapi5 { get; set; }
        public string? Cneden5 { get; set; }
        public DateTime? Gtarih6 { get; set; }
        public DateTime? Gzaman6 { get; set; }
        public string? Gkapi6 { get; set; }
        public string? Gneden6 { get; set; }
        public DateTime? Ctarih6 { get; set; }
        public DateTime? Czaman6 { get; set; }
        public string? Ckapi6 { get; set; }
        public string? Cneden6 { get; set; }
        public DateTime? Gtarih7 { get; set; }
        public DateTime? Gzaman7 { get; set; }
        public string? Gkapi7 { get; set; }
        public string? Gneden7 { get; set; }
        public DateTime? Ctarih7 { get; set; }
        public DateTime? Czaman7 { get; set; }
        public string? Ckapi7 { get; set; }
        public string? Cneden7 { get; set; }
        public DateTime? Gtarih8 { get; set; }
        public DateTime? Gzaman8 { get; set; }
        public string? Gkapi8 { get; set; }
        public string? Gneden8 { get; set; }
        public DateTime? Ctarih8 { get; set; }
        public DateTime? Czaman8 { get; set; }
        public string? Ckapi8 { get; set; }
        public string? Cneden8 { get; set; }
        public DateTime? Gtarih9 { get; set; }
        public DateTime? Gzaman9 { get; set; }
        public string? Gkapi9 { get; set; }
        public string? Gneden9 { get; set; }
        public DateTime? Ctarih9 { get; set; }
        public DateTime? Czaman9 { get; set; }
        public string? Ckapi9 { get; set; }
        public string? Cneden9 { get; set; }
        public DateTime? Gtarih10 { get; set; }
        public DateTime? Gzaman10 { get; set; }
        public string? Gkapi10 { get; set; }
        public string? Gneden10 { get; set; }
        public DateTime? Ctarih10 { get; set; }
        public DateTime? Czaman10 { get; set; }
        public string? Ckapi10 { get; set; }
        public string? Cneden10 { get; set; }
        public DateTime? Gtarih11 { get; set; }
        public DateTime? Gzaman11 { get; set; }
        public string? Gkapi11 { get; set; }
        public string? Gneden11 { get; set; }
        public DateTime? Ctarih11 { get; set; }
        public DateTime? Czaman11 { get; set; }
        public string? Ckapi11 { get; set; }
        public string? Cneden11 { get; set; }
        public DateTime? Gtarih12 { get; set; }
        public DateTime? Gzaman12 { get; set; }
        public string? Gkapi12 { get; set; }
        public string? Gneden12 { get; set; }
        public DateTime? Ctarih12 { get; set; }
        public DateTime? Czaman12 { get; set; }
        public string? Ckapi12 { get; set; }
        public string? Cneden12 { get; set; }
        public DateTime? Gtarih13 { get; set; }
        public DateTime? Gzaman13 { get; set; }
        public string? Gkapi13 { get; set; }
        public string? Gneden13 { get; set; }
        public DateTime? Ctarih13 { get; set; }
        public DateTime? Czaman13 { get; set; }
        public string? Ckapi13 { get; set; }
        public string? Cneden13 { get; set; }
        public DateTime? Gtarih14 { get; set; }
        public DateTime? Gzaman14 { get; set; }
        public string? Gkapi14 { get; set; }
        public string? Gneden14 { get; set; }
        public DateTime? Ctarih14 { get; set; }
        public DateTime? Czaman14 { get; set; }
        public string? Ckapi14 { get; set; }
        public string? Cneden14 { get; set; }
        public DateTime? Gtarih15 { get; set; }
        public DateTime? Gzaman15 { get; set; }
        public string? Gkapi15 { get; set; }
        public string? Gneden15 { get; set; }
        public DateTime? Ctarih15 { get; set; }
        public DateTime? Czaman15 { get; set; }
        public string? Ckapi15 { get; set; }
        public string? Cneden15 { get; set; }
        public string? Fark { get; set; }
        public string? Aciklama { get; set; }
        public DateTime? Gecsure { get; set; }
        public DateTime? Erkensure { get; set; }
        public string? Turu { get; set; }
        public string? Srkodu { get; set; }
    }
}
